name       : hyperfine
version    : 1.11.0
release    : 2
source     :
    - https://github.com/sharkdp/hyperfine/archive/v1.11.0.tar.gz : 740f4826f0933c693fb281e3542d312da9ccc8fd68cebe883359a8085ddd77e9
homepage   : https://github.com/sharkdp/hyperfine
license    :
    - Apache-2.0
    - MIT
component  : system.utils
networking : yes
summary    : A command-line benchmarking tool
description: |
    A command-line benchmarking tool.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/hyperfine $installdir/usr/bin/hyperfine
    install -Dm00644 doc/hyperfine.1 $installdir/usr/share/man/man1/hyperfine.1
    install -Dm00644 target/release/build/hyperfine-*/out/hyperfine.bash $installdir/usr/share/bash-completion/completions/hyperfine
    install -Dm00644 target/release/build/hyperfine-*/out/_hyperfine $installdir/usr/share/zsh/site-functions/_hyperfine
    install -Dm00644 target/release/build/hyperfine-*/out/hyperfine.fish $installdir/usr/share/fish/vendor_completions.d/hyperfine.fish
check      : |
    cargo test --all
